version: '3.1'
services:
  db:
    image: tutum/mongodb
    restart: always
    ports:
      - 27017:27017
      - 28017:28017
    environment:
      AUTH: "no"
    networks:
      - mongo-stack-dev-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: "db"
    networks:
      - mongo-stack-dev-network

networks: 
  mongo-stack-dev-network:
    driver: bridge