version: '3.1'
services:
  db:
    image: postgres:11.5
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: dev123
      POSTGRES_DB: database-dev
    volumes:
        - ~/docker-services/postgresql/data:/var/lib/postgresql/data
    networks:
      - pgdata-stack-dev-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    networks:
      - pgdata-stack-dev-network

networks: 
  pgdata-stack-dev-network:
    driver: bridge